### Upload image
POST http://localhost:4000/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.jpg"
Content-Type: image/jpg

< ./assets/main.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Get the image itself
DELETE http://localhost:4000/image/6a6c899c-af3a-4621-84f8-8f50f5224e54.jpg
### Get the image itself
GET http://localhost:4000/image/6a6c899c-af3a-4621-84f8-8f50f5224e54.jpg
### Get the coverted version
GET http://localhost:4000/image/6a6c899c-af3a-4621-84f8-8f50f5224e54.jpg
  ?size=xs