### GET POSTs
GET http://localhost:4000/post
  ?limit=10
  &skip=0

### GET A SINGLE POST
GET http://localhost:4000/post/6375177357552633c58dc4fd


### CREATE A POST
POST http://localhost:4000/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM3NTE3NTM1NzU1MjYzM2M1OGRjNGY3.bCGEcBsfxGiWBUKPBae55oAo4Eb8lMrXA26ZwQXOzP8

{
  "title":"How to speak!",
  "body":"post validation failed: createdBy: Path `createdBy` is required., body: Path `body` is required., title: Path `title` is required."
}
### DELETE A POST
DELETE  http://localhost:4000/post/6375177357552633c58dc4fd
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM3NTE3NTM1NzU1MjYzM2M1OGRjNGY3.bCGEcBsfxGiWBUKPBae55oAo4Eb8lMrXA26ZwQXOzP8


### Upldate A POST
PATCH  http://localhost:4000/post/6375177357552633c58dc4fd
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM3NTE3NTM1NzU1MjYzM2M1OGRjNGY3.bCGEcBsfxGiWBUKPBae55oAo4Eb8lMrXA26ZwQXOzP8

{
  "title":"Cosmopolitan"
}