### GET USERS
GET http://localhost:4000/user
  ?limit=2
### GET USERS
GET http://localhost:4000/user
  ?search=soft
### GET USERS
GET http://localhost:4000/user
  ?title=sta

### GET A Single USER
GET http://localhost:4000/user/6375175357552633c58dc4f7

### CREATE A USER
POST http://localhost:4000/user
Content-Type: application/json

{
  "username":"farid",
  "title":"CEO",
  "password":"1234",
  "email":"sf@gmail.com",
  "fullName":"Farid Niazi"
}

### DELETE A USER
DELETE  http://localhost:4000/user
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM3NGZiZWYyZWUwZGNlZDgyYTVkMzU2.Cw4A0LXP_n9BtgFU7JgPesXOFtz3eYZfgRVfSem9X80


### UPDATE A USER
PATCH  http://localhost:4000/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM3NGZiZWYyZWUwZGNlZDgyYTVkMzU2.Cw4A0LXP_n9BtgFU7JgPesXOFtz3eYZfgRVfSem9X80


{
  "fullName":"Farid Nazia"
}