### Upload image
POST http://localhost:4000/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.jpg"
Content-Type: image/jpg

< ./assets/main.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Get the image itself
GET http://localhost:4000/image/fff9dfbf-8e92-488e-86f4-06e032c06a6b.jpg
### Get the image itself
GET http://localhost:4000/image/beach.jpg
### Get the coverted version
GET http://localhost:4000/image/fff9dfbf-8e92-488e-86f4-06e032c06a6b.jpg
  ?size=xs