### GET POSTs
GET http://localhost:4000/post
  ?limit=10
  &skip=0

### GET A SINGLE POST
GET http://localhost:4000/post/636e207b72db0cbb7f588de5


### CREATE A POST
POST http://localhost:4000/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM2ZTFlMmIxZTU5YTg3YTM1OTQ4ZDdh.tbX7WvsOtd1xFcvvGx-MyeQDfgkfG65cuI-NUhk4y-c


{
  "title":"How to speak!",
  "body":"post validation failed: createdBy: Path `createdBy` is required., body: Path `body` is required., title: Path `title` is required."
}
### DELETE A POST
DELETE  http://localhost:4000/post/636e1ea81e59a87a35948d87

### Upldate A POST
PATCH  http://localhost:4000/post/636e207b72db0cbb7f588de5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.NjM2ZTFlMmIxZTU5YTg3YTM1OTQ4ZDdh.tbX7WvsOtd1xFcvvGx-MyeQDfgkfG65cuI-NUhk4y-c


{
  "title":"Cosmopolitan"
}