### GET USERS
GET http://localhost:4000/user

### GET A Single USER
GET http://localhost:4000/user/636d09f5baeef495029a4a16

### CREATE A USER
POST http://localhost:4000/user
Content-Type: application/json

{
  "username":"ajmir",
  "password":"xxx",
  "crf":"sf@gmail.com",
  "fullName":"Ajmir Raziqi"
}
### DELETE A USER
DELETE  http://localhost:4000/user/636bca16952778e76a72606f

### CREATE A USER
PATCH  http://localhost:4000/user/636bca16952778e76a72606f
Content-Type: application/json

{
  "email":"a@gmail.com"
}