### GET USERS
GET http://localhost:4000/user

### GET A Single USER
GET http://localhost:4000/user/636d09f5baeef495029a4a16

### CREATE A USER
POST http://localhost:4000/user
Content-Type: application/json

{
  "username":"ajmir",
  "password":"xxx",
  "crf":"sf@gmail.com",
  "fullName":"Ajmir Raziqi"
}
### DELETE A USER
DELETE  http://localhost:4000/user
Authorization: token eyJhbGciOiJIUzI1NiJ9.NjM2ZDA5ZjViYWVlZjQ5NTAyOWE0YTE2.5fusx_l5kQlH88oa5DUnJ0f-zc0mXa6xdmt3ZRsRTbo


### UPDATE A USER
PATCH  http://localhost:4000/user
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiJ9.NjM2ZDA5ZjViYWVlZjQ5NTAyOWE0YTE2.5fusx_l5kQlH88oa5DUnJ0f-zc0mXa6xdmt3ZRsRTbo


{
  "username":"bobo@gmail.com"
}