### GET USERS
GET http://localhost:4000/user
  ?limit=2

### GET A Single USER
GET http://localhost:4000/user/636e1e2b1e59a87a35948d7a
  ?limit=1

### CREATE A USER
POST http://localhost:4000/user
Content-Type: application/json

{
  "username":"ajmir",
  "password":"xxx",
  "email":"sf@gmail.com",
  "fullName":"Ajmir Raziqi"
}
### DELETE A USER
DELETE  http://localhost:4000/user
Authorization: token eyJhbGciOiJIUzI1NiJ9.NjM2ZDA5ZjViYWVlZjQ5NTAyOWE0YTE2.5fusx_l5kQlH88oa5DUnJ0f-zc0mXa6xdmt3ZRsRTbo


### UPDATE A USER
PATCH  http://localhost:4000/user
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiJ9.NjM2ZTFlMmIxZTU5YTg3YTM1OTQ4ZDdh.tbX7WvsOtd1xFcvvGx-MyeQDfgkfG65cuI-NUhk4y-c


{
  "username":"ajmir.n"
}